### ISSUE TITLE
Catch up on GL extension support from core

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-cocoa#76]
There are several changes in core to improve the support/use of various GL extensions. These need to brought to iOS too.

List of changes:
- [ ] 24 bit packed depth/stencil - https://github.com/mapbox/mapbox-gl-cocoa/issues/74
- [ ] GL debug context/logging - https://github.com/mapbox/mapbox-gl-native/issues/668
- [ ] compiled shader caching - https://github.com/mapbox/mapbox-gl-native/issues/588

**Comment by ljbade** [comment]
We are no longer doing this. https://github.com/mapbox/mapbox-gl-native/pull/778
